### ISSUE TITLE
Customizable mapping between hand tracking gestures and controller buttons

### ISSUE THREAD

**Issue by JackD83** [alvr-org/ALVR#111]
Hey @A3yuu

I saw your fork for hand tracking using ALVR and the index emulation. I'm very excited about this. Did it work? Unfortunately, I have no other way of contacting you. I'm always open for pull request. 

Looking forward to see some updates!

**Comment by A3yuu** [comment]
ごきげんよう@JackD83
ALVRのサポート継続ありがとう。素晴らしいソフトウェアだ。

SteamVR上で指を動かすことはできる。VRChatでも指が曲がる。でもNot Workだ。それは次の技術的問題と仕様的問題による。
■技術的問題
手のとコントローラの位置合わせがうまく行かない。なんか右90度に曲がるしちょっと位置も変。
一部の0番目のボーンがOculusで存在しないために手の再現が良くない。
ジェスチャーを新規定義するのがわからんので、ボタンが足りない。
■仕様的問題
人間の手にはジョイスティックやボタンがついてない。

よってまだプルリクエストできるほど仕上がっていない。なぐり書きコードだしね(｡>﹏<｡)

Good work @JackD83
Thank you for continuing to support ALVR. Great software.

This can move finger on SteamVR. And VRChat. But not work. It depends on the following technical and specification issues.
■ Technical issues
The alignment between the hand and the controller does not go well. It turns 90 degrees to the right and the position is a little strange.
Hand reproduction is poor because some 0th bones are missing in Oculus.
I don't know how to define a new gesture, so there are not enough buttons.
■ Specification issues
Human hands do not have joysticks or buttons. 

Therefore, it is not yet finished so that a pull request can be made. It's a scribble code(｡>﹏<｡)

**Comment by T3ER** [comment]
> ごきげんよう@JackD83
> ALVRのサポート継続ありがとう。素晴らしいソフトウェアだ。
> 
> SteamVR上で指を動かすことはできる。VRChatでも指が曲がる。でもNot Workだ。それは次の技術的問題と仕様的問題による。
> ■技術的問題
> 手のとコントローラの位置合わせがうまく行かない。なんか右90度に曲がるしちょっと位置も変。
> 一部の0番目のボーンがOculusで存在しないために手の再現が良くない。
> ジェスチャーを新規定義するのがわからんので、ボタンが足りない。
> ■仕様的問題
> 人間の手にはジョイスティックやボタンがついてない。
> 
> よってまだプルリクエストできるほど仕上がっていない。なぐり書きコードだしね(｡>﹏<｡)
> 
> Good work @JackD83
> Thank you for continuing to support ALVR. Great software.
> 
> This can move finger on SteamVR. And VRChat. But not work. It depends on the following technical and specification issues.
> ■ Technical issues
> The alignment between the hand and the controller does not go well. It turns 90 degrees to the right and the position is a little strange.
> Hand reproduction is poor because some 0th bones are missing in Oculus.
> I don't know how to define a new gesture, so there are not enough buttons.
> ■ Specification issues
> Human hands do not have joysticks or buttons.
> 
> Therefore, it is not yet finished so that a pull request can be made. It's a scribble code(｡>﹏<｡)

I tried out the release on your fork. I agree on the issues. My hands kept flying around randomly sometimes and I accidently used the buttons on differenr pinches. The movement of hands wasn't smooth, like it jumps instantly to the next updated position of hands. The tracking is always fine with same movements of my hands in apps or quest's home. My quest is on V13.
From what I tested, there are 3 buttons assigned to gestures, trigger (index + thumb pinch), A button (middle + thumb pinch) and menu button. (ring and middle + thumb)
Neverthless it's really cool and I'm looking forward to see what and how we can get this working.

**Comment by CutionTag** [comment]
Hey! So I was fiddling with A3yuu's hand tracking branch and was thinking of ways we could emulate joysticks without, yknow having a joystick. Is there a way to track the oculus controller while also simultaneously tracking your hands? I haven't looked at any of the SDK for the hand tracking, but if it's possible to track both, what if a user strapped a controller to each leg or shoved them in their pockets? You could then track where the persons legs are for movement! Like, I know strapping a controller to your leg isn't  very comfy, but it's an idea atleast. I know the if the sensors don't see the controllers, it uses the accell/gyro in the controllers to guess where they are. Couldn't you theoretically use that same guessing to check if a user lifts a leg up or down?

**Comment by A3yuu** [comment]
コントローラーと手の同時トラッキングはSDK上で不可能だと思う。(試したことはない。是非試してみてほしい。)
また、QuestはトラッキングにHMDのカメラを使うので下記になる。
・ポケットの中：見えないのでトラッキングできない
・足：殆ど見えないのでトラッキングは困難
○加速度センサによる位置推定
*ジャイロはドリフトするので長期的なアンカーポイントには利用できない
非常に難しい。IKの論文を読んだなら理論上できることはわかるが、Katlocoを知っていれば事実上困難であることは理解できると思う。
○加速・ジャイロセンサによる行動推定
長期的な研究を行えば、Katlocoが行っているように、足を振っているかを見て、歩くことはできるかもしれない。

I think that simultaneous tracking of controller and hand is impossible on SDK. (I have never tried it. Please try it CutionTag.)
Also, Quest uses an HMD camera for tracking, so it is as follows.
- In pocket: Cannot track because it is invisible
- Feet: tracking is difficult because it is hardly visible
○ Position estimation by acceleration sensor
* Gyro drifts and cannot be used for long-term anchor points
extremely difficult. If you read an IK paper, you know what you can do in theory, but if you know Katloco, you can understand that it's practically difficult.
○ Behavior estimation by acceleration / gyro sensor
With long-term research, you might be able to walk and see if you are waving, as Katloco does.

**Comment by zarik5** [comment]
@CutionTag I wouldn't say that that your idea is impossible, but it is hard to make a system that consistently does what the user wants. If done well it should be possible to track the legs and the rest of the body with non positional sensors (that is accelerometer + gyroscope + magnetometer). If using a sensor for each bone, the problem simplifies to forward kinematics. If using less sensors (for example one for each leg) it is still possible using machine learning and a prior on the space of human poses (take a look at [this](https://ps.is.mpg.de/publications/dip_sa18)). With another bit of machine learning magic one could make a system that translates leg movement to joystick input, but again what's really hard is to make a system that works reliably.
Instead another way to emulate the joystick could be the gesture "pinch and drag", but testing is required to see if this is sufficiently ergonomic.

**Comment by JackD83** [comment]
I think that the way hand tracking is currently implemented in ALVR is just a prove of concept. We will never be able to play games that where designed specifically for the index controller and the joystick. 
What we could do is playing games and running software that was designed for hand tracking with the magic leap or some kind of glove that captures your movement, but the software still has to support it.

If and when the Rift S supports some kind of hand tracking, we will see more and more software that will ditch the controllers to have a more natural interaction in VR.

Full body tracking is something that a lot of people try to accomplish and is no easy task without an external tracker

**Comment by amg-12** [comment]
Is it possible to map the hand skeleton directly to an in-game hand model rather than trying to emulate a controller? This could be a very cool proof of concept in a game like Half-Life: Alyx. You couldn't walk or hold things since there would be no button inputs but you would be able to move your fingers freely and to play the piano.

**Comment by zarik5** [comment]
While not perfect, this has been implemented. Closing
