### ISSUE TITLE
Head tracking delayed by 5+ after head position is reset in steamVR [Linux]

### ISSUE THREAD

**Issue by davigamer987** [alvr-org/ALVR#1133]
## Description

Head Tracking is broken only inside games, In steamvr home head tracking works fine but when i open a game (I tried beat saber, google earth and vivecraft) It breaks (Game runs fine in pc), On the headset if i move my head i can see the edge of the rendring and a bunch of glitchy stuff and the tracking is delayed by more than 5 seconds, It's unplayable. On the alvr dashboard there are very weird lag spikes ([Image](https://media.discordapp.net/attachments/935455291896631306/1000103190022332517/unknown.png)) I check logs and it says i'm using VAAPI, Also the network has ideal conditions (Router in same room, Wifi 6, Pc connected with Ethernet) so it should work.

## General Troubleshooting
- [Yes ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [Yes ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: Ryzen 7 5800x

**GPU**: Rx 6900 Xt 

**Audio**:
![unknown](https://user-images.githubusercontent.com/68574209/180502364-3a40b433-5a4e-4603-85aa-4d39d8df3a44.png)

### Installation
![unknown](https://user-images.githubusercontent.com/68574209/180502387-e5697e08-65d2-4b34-878c-7ae9dc86b385.png)

**ALVR Version**:  1.18.2.3

**SteamVR Version**: 1.23.6 (Latest Stable Version)

**Install Type**:
- [ AUR] Packaged (`exe`, `deb`, `rpm`, etc)
- [ AUR] Portable (`zip`)
- [ AUR] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Arch linux (Rolling release)

**Comment by davigamer987** [comment]
Hw probe: https://linux-hardware.org/?probe=0b6a41a9b8

**Comment by davigamer987** [comment]
I tried lowering Bitrate, resolution and also tried changing from tcp to udp. didn't work

**Comment by CrazyVito11** [comment]
I can confirm I also have this issue, but only if I reset my position within SteamVR. If I don't do that, it's fine.

**Comment by davigamer987** [comment]
But in all game i spawn facing backwards, so i need to reset the posistion

**Comment by famellad** [comment]
I too have this problem when playing Euro Truck Simulator 2, as I spawn way above the driver's sit, I have to reset the view, but after doing that the game just becomes an unplayable lagfest

**Comment by famellad** [comment]
Ok, by installing **OVR Advanced Settings** you can manually set the camera offset and rotation, and doing this I have discovered that this problem only arises when changing the **rotation** offset, changing any of the position values works as expected and introduces no lag.
Also this problem is only present when using the SteamVR recentering, moving and rotating the room around for example in the Beat Saber options works perfectly fine.

**Comment by Espionage724** [comment]
Have you tried switching from HEVC to H.264? I noticed that tracking lag a little bit ago with a 6600 XT, and it went away after switching to H.264.

**Comment by davigamer987** [comment]
> Can op confirm this is still an issue?

I don't own a quest 2 anymore, so I can't test

**Comment by Vixea** [comment]
Ok I'm going to close as not planned

**Comment by CrazyVito11** [comment]
I can probably test it sometime tonight

**Comment by CrazyVito11** [comment]
@Vixea The experience is a lot better on the new update, and was able to actually play Bonelab _(only tested for around 10 minutes)_ I was able to reset my view in SteamVR as well.

I only changed the following settings compared to default:
- Resolution: High (5184)
- Preferred framerate: 120hz
- Linux async reprojection: On

The only issues I encountered, are:
- The tracking "jitters" a lot when starting a game (not sure if that is because of the sudden bit rate spike, or the CPU being loaded)
- The stream "grayed out" once completely and was like that for probably 30 seconds before slowly recovering from the corruption
- The stream fully cut out once after the game render delay became too high _(game was still running fine on the monitor, but not in the headset)_, I've attached a screenshot of when that happened.

![image](https://github.com/alvr-org/ALVR/assets/31567466/d64f40c9-188a-46ae-889e-266259698396)
![image](https://github.com/alvr-org/ALVR/assets/31567466/8862dafd-55a5-4d12-bf73-e62c2653f37c)

---

All in all, very good progress! I assume that most of these issues are probably caused by me not having tweaked the settings yet, and being on a slow WiFi 4 network (5Ghz).

**Comment by Vixea** [comment]
Do not use high there isn't a point on the quest 2 as the default resolution is tuned to the quest 2

**Comment by CrazyVito11** [comment]
Setting it to high seemed to improve the quality for me, but that might be a coincidence as it's using the adaptive bit rate.
I'll try tweaking the settings a bit probably tomorrow.

**Comment by CrazyVito11** [comment]
I tried running it today using a Link cable, and while it did look very sharp and was very responsive, the same issues as before appeared.

The only one that didn't appear this time, was the total video corruption. So that was probably just the WiFi network yesterday not really being up to the task.

As for the jitter tracking while launching games, I did notice today that the feed also has a bit of corruption during that time. Maybe that indicates something? It was just some random pixels showing up while looking around primarily.

I've added a recording of me starting a game. It's a bit hard to see, but you can see while it's starting the tracking is a bit twitchy, once the Valve intro appears, it's a lot smoother. You can also see the corruption I was talking about while it is loading.

https://github.com/alvr-org/ALVR/assets/31567466/cd8cb7ec-82d2-4529-b887-0fa217b5d7e3

**Comment by Vixea** [comment]
Yea, all this stuff is unactionable with a meta bug or just how SteamVR works when loading things
