### ISSUE TITLE
ALVR only lists audio inputs as sources to stream

### ISSUE THREAD

**Issue by Soggy-Pancake** [alvr-org/ALVR#1136]
ALVR doesn't give me the option to select any of my audio outputs and only finds inputs.

**Comment by crapStone** [comment]
Can you please give more information about your setup?

**Comment by Soggy-Pancake** [comment]
Im running manjaro with a 1080 and amd r5 5600x

**Comment by Rodancoci** [comment]
I'm experiencing the same on Arch Linux with ALVR 19.0.0_dev00+nightly.2022.08.16-1.

Instead of sending the default **output** device audio (PC speakers in my case) to my Quest 2 speakers, it sends the default **input** device audio (microphone in my case). Basically, the HMD speakers just play whatever the microphone hears instead of the desktop audio.

**Comment by Redd56** [comment]
Id sugest installing pavucontrol and via its gui heading to the recording tab and manualy selecing the one you want for alvr. 
It will remember this even if you shut down alvr, just gotta do it each reboot
