### ISSUE TITLE
This is a good up but i'm a mac user and sadly i can't use it

### ISSUE THREAD

**Issue by ertikow2** [alvr-org/ALVR#1147]
## General Troubleshooting
- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:

**GPU**:

**Audio**:

### Installation
**ALVR Version**:

**SteamVR Version**:

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

**Comment by crapStone** [comment]
Are you ok with me changing the title and description to a feature request for macOS cupport?

**Comment by jcrm1** [comment]
The server compiles for me on macOS 12.6 M1. None of the old SteamVR Mac beta branches work with it, though. SteamVR just crashes silently once you start `alvr_launcher`. The ALVR window changes to "Waiting for server to load... Please wait for multiple restarts". It also doesn't build the compositor wrapper or vulkan layer or copy the vulkan layer manifest, ffmpeg binaries, or ffmpeg shared lib dependencies because those are in `if cfg!(target_os = "OS")` blocks in `xtask/src/build.rs`. It's interesting that it gets this far, though.

**Comment by zarik5** [comment]
Some conditional compilation flags for macos were inserted by me, to ease the development since my main dev machine is an M1 mac. Most of the code in the repository is made to compile on the mac without actually be able to make use of it.

**Comment by jcrm1** [comment]
I'm investigating porting this to macOS- it already works, for the most part, thanks to your work I assume. I realize this will likely also require adding a VideoToolbox encoder. My main goal for this is to run Vivecraft, which seems to be one of the last few VR games with macOS support.
No dashboard appears (chromium installed and on PATH)
The launcher shows "Waiting for server..."
 I can't access the webpage (even at http://127.0.0.1:8082), and any debug println! messages I put in `init()` in `alvr/server/src/lib.rs` don't show up. I can confirm that `web_server` in `alvr/server/src/web_server.rs` is not running as a result of the `init()` issue.
I can also confirm that the loop the server is stuck in is `launcher_lifecycle` in  `alvr/launcher/src/main.rs`. `The println!("Marker")` statement is all that triggers- because the webserver is not running, the loop never hits `break`.
```
let maybe_response = request_agent.get("http://127.0.0.1:8082/index.html").call();
println!("Marker");
if let Ok(response) = maybe_response {
    if response.status() == 200 {
        state.lock().unwrap().view = View::Close;
        break;
    }
}
```
x86_64-apple-darwin

Any thoughts? To me, it almost seems like the dylib is never loading... but I'm pretty sure it is, because I tried using `DYLD_INSERT_LIBRARIES` as well.
