### ISSUE TITLE
ALVR causes GPU to crash and fail to recover, forcing a hard reboot

### ISSUE THREAD

**Issue by KiranWells** [alvr-org/ALVR#1286]
## Description

When ALVR first creates a connection, it will sometimes cause the screen to lose signal permanently. I am not able to get a picture back in any way without hard rebooting the computer (holding down the power button). I do not see anything that seems relevant in the logs (i.e. no consistent error or other message between repeated crashes), and the `crash_log.txt` is empty. However, I ran a dmesg and saw some relevant output:

```
$ sudo dmesg -w | tee dmesg.log

[  930.862542] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx_0.0.0 timeout, signaled seq=1019841, emitted s
eq=1019843
[  930.862719] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* Process information: process VRChat.exe pid 10884 threa
d dxvk-submit pid 10954
[  930.862872] amdgpu 0000:0b:00.0: amdgpu: GPU reset begin!
[  931.179576] amdgpu 0000:0b:00.0: [drm:amdgpu_ring_test_helper [amdgpu]] *ERROR* ring kiq_2.1.0 test failed (-1
10)
[  931.179703] [drm:gfx_v10_0_hw_fini [amdgpu]] *ERROR* KGQ disable failed
[  931.442775] [drm:gfx_v10_0_hw_fini [amdgpu]] *ERROR* failed to halt cp gfx
[  931.467978] [drm] free PSP TMR buffer
...
```

For the full log, see [here](https://pastebin.com/K3JEFtWU). What I believe to be relevant information starts at time 930.862542.

It seems like something is causing the GPU driver to crash unrecoverable. This usually occurs immediately after the client connects, but this `dmesg` is of a run where I successfully started the stream, then the screen blacked out some time while I was streaming (from the log it seems to be roughly 30 seconds after I reconnected to my network).

This behavior seems to be the same issue that was mentioned in #777, but that issue was never addressed.

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

[link](https://linux-hardware.org/?probe=ff119f84e6)

### Installation
**ALVR Version**: 
```
$ yay -Qi alvr
Name            : alvr
Version         : 19.0.0.r0.g1215da95-1
...
```

**SteamVR Version**: 1.25.1 I think?

**Install Type**:
- [X] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

```
$ grep PRETTY_NAME /etc/os-release
PRETTY_NAME="Arch Linux"
```

**Comment by Timocop** [comment]
A Radeon RX 6000 series user nice, do you use by any chance the stable AMD GPU drivers? (22.5.1) *(Im not sure if its any different on Linux.)*
ALVR v19 updated the AMF SDK and the beta driver is required (higher or equal than 22.7.1).

**Comment by KiranWells** [comment]
I use the drivers in the `mesa` package, along with a few related driver packages for video acceleration. The Arch Linux rolling release version of mesa is at version `22.2.3-1`, but I am not sure if this corresponds with the version numbers you are referring to. The git version is at `23.0.0_devel...`; however it requires manual recompilation. If I have time, I can try running off of that and see if the issue is resolved.

**Comment by KiranWells** [comment]
I was unable to get a separate package (amdgpu pro amf) working. Steam VR refused to start, likely due to the existence of two different vulkan drivers. However, I believe mesa should be up to date if it is the same version as the amdgpu pro drivers (22.20.4)

**Comment by M3TIOR** [comment]
You're using Arch Linux right? If you're using the AMD provided driver, the method by which you change your driver shifts. Did you try looking at the arch wiki page for amdgpu when you were trying to get it working? Have you tried using all three of the different AMD provided ones? Pretty sure the mesa driver's version does not correlate at all with the amdgpu driver because mesa's an independent org. 

I doubt ALVR is responsible for this issue if it's making your screen go black. It's most likely a flaw in a specific vulkan API function that ALVR depends on inside whatever driver you were using. Also I'd like to point out that Arch isn't the most stable due to their release pattern. There are a myriad of problems that can be hard to isolate when you're not running a containerized instance with strictly controlled dependencies. Ubuntu and Debian derivatives mitigate this by waiting several years to validate software stability before releasing it to their users. The power of Arch comes with consequences.

Though that said, since you're not in a container, setting one of the environment variables detailed in the Arch Wiki should allow you to swap your drivers on a per-application basis. If after compiling the amdgpu beta driver, you ran something like `make install` to modify your system state and make the new driver accessible, it's possible that the new driver is missing the a vulkan feature that ALVR needs. I've run into this problem in a different application with the amdgpu open source driver myself. As far as I know, the mesa driver has more features than any of the amd provided ones; though iirc their drivers are reverse-engineered and not as supposedly dependable as the amd provided ones.

When you swapped the driver, did you try enabling asynchronous reprojection in ALVR? Did ALVR even finish starting up? You said that SteamVR refused to start, as opposed to throwing an error code at you like 307 or something. When you say failed to start, I assume you meant SteamVR silently failed and didn't show up at all.

**Comment by M3TIOR** [comment]
Also, you said your screen went black "sometimes". When's the last time you did a stress test on the GPU? It's not too old but you could have lost the silicon lottery and wound up with a faulty chip. VR games are notoriously hard on the GPU. If you only play VR games and it only fails under an intense load, that may be the issue too.

**Comment by nowrep** [comment]
GPU crash has most likely nothing to do with ALVR, you should report your issue to amdgpu bug tracker.
Also you can just restart your compositor (or X server in case you are on X11) instead of rebooting machine.

**Comment by KiranWells** [comment]
Thank you for all of the help addressing this issue.

> GPU crash has most likely nothing to do with ALVR, you should report your issue to amdgpu bug tracker.

You might be right, I will do that.

>  Also you can just restart your compositor (or X server in case you are on X11) instead of rebooting machine.

No; the screen loses signal. I have tried blindly killing my window manager with a keybind (that would have caused it to restart with the way my machine is set up), and that had no effect. I also tried pressing `Ctrl-Alt-F2` to go to tty2 and bypass the x server entirely, but that did not work. The only way I could get any display back to my monitor was by restarting. Also, on one occasion it seemed like the streamed video to the headset continued after the screen lost signal; I have not had this happen again, though.

> did you try enabling asynchronous reprojection in ALVR? 

Which setting is this? I don't see "asynchronous reprojection" anywhere in the wiki.

> Did ALVR even finish starting up? You said that SteamVR refused to start, as opposed to throwing an error code at you like 307 or something. When you say failed to start, I assume you meant SteamVR silently failed and didn't show up at all.

Sorry if I was not clear; Steam VR would always produce a 307 error, and the ALVR server would be unreachable. This has happened before, but was usually fixed by restarting ALVR. This time, I was only able to fix it by uninstalling the amdgpu pro vulkan package.

As for your other driver-related advice, I will try using the different drivers available (`mesa`, `mesa-git`, and `amdgpu-pro`). From what I have seen in the Arch wiki, the mesa drivers are fully supported by AMD and the pro drivers are only packaged for people on LTS distributions, but there may be something I am missing.

> When's the last time you did a stress test on the GPU? It's not too old but you could have lost the silicon lottery and wound up with a faulty chip.

This GPU is only 1.5 months old; I have also run other applications that fully utilize the GPU, including demanding non-vr games and the Blender Cycles renderer. If you have a different stress test you would recommend, I would be happy to run it.

**Comment by KiranWells** [comment]
I spent most of the day debugging this, and I can confirm the bug still occurs on the `mesa-git` installation. I could not get past the SteamVR 307 error on stable ALVR with amdgpu pro drivers or amdvlk drivers. After trying the other drivers, I started to get a 306 error on mesa as well. Moving to the latest nightly build of ALVR fixed that issue somehow, but I did get a black screen bug once.

Currently, I have a mostly-working setup with mesa-git and ALVR 20.0 on both desktop and quest. Because the black screen also occurred on mesa-git, I am going to submit a bug report on the mesa repository.

**Comment by M3TIOR** [comment]
I was asking about async reprojection because on the previous stable releases, while it may drop the visual stability, it seems to have a history of increasing driver compatibility. Also different linux distros use different default session TTYs and as a result will have their compositor / X11 in that session. Just trying `CTRL+ALT+F{number}` once may not be enough because you may inadvertently be hitting the F key for the session you're currently in. That said I tried it on my laptop which also runs Arch and the default tty is tty1 so what you did probably should have worked.

I mean, breaking down the first error in your dmesg output
> `[  931.179703] [drm:gfx_v10_0_hw_fini [amdgpu]] *ERROR* KGQ disable failed` 
It looks like for whatever reason, after the GPU is forced to reset (presumably because ALVR did something wrong); it's failing to reinitialize the GPU because of something happening in the DRM of the driver. (gfx -> graphics; hw -> hardware; fini -> finalize initialization) I've never crawled into the internals of the driver to know how accurate my expansion is but as a C programmer with 6 years of experience, I think that's probably what''s going on. It very well could be that ALVR is introducing undefined behavior via a malformed API call, causing your driver to crash. That's gonna be hell to find though.

**Comment by luizffgv** [comment]
Also happening with an R9 270X on Arch, same ALVR version. The video also has artifacts from the start until the crash, but I'm not sure if it's related to this issue. Everything works perfectly on Windows.
I can provide logs or more info if requested.

**Comment by mittorn** [comment]
Unstale
