### ISSUE TITLE
how can i get it to work on linux it will not let me open in the archive manager

### ISSUE THREAD

**Issue by yerper13** [alvr-org/ALVR#1591]
## General Troubleshooting
- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:

**GPU**:

**Audio**:

### Installation
**ALVR Version**:

**SteamVR Version**:

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

**Comment by TheGreatMcPain** [comment]
Have you tried the Appimage from the [releases page](https://github.com/alvr-org/ALVR/releases)?

You might need to give the Appimage execute permissions which can be done through your file manager, or from the terminal by running `chmod +x /path/to/ALVR-x86_64.AppImage`.

After that you should be able to run it like any other executable.

*Looks like the Wiki pages are still pretty outdated, since it refers to a portable `tar.gz` that doesn't exist.*
