### ISSUE TITLE
关于18.2.3APK版本运行闪退与19.1.1和20.0.0版本使用时串流画面模糊，马赛克的问题

### ISSUE THREAD

**Issue by fouable** [alvr-org/ALVR#1668]
## Description

 我的Oculus Quest2设备在安装了18.2.3版本之后运行会闪退，无法运行
在安装了19.1.1版本与20.0.0版本的使用过程中，串流使用第三方应用出现了画面马赛克的问题

## General Troubleshooting
- [ √] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [√ ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`
小米游戏本， Meta Quest 2（系统版本可能较新）
**CPU**:
i7 12700
**GPU**:
3060（移动端）
**Audio**:

### Installation
**ALVR Version**:
18.2.3
19.1.1
20.0.0
**SteamVR Version**:
最新版本1.26.2
**Install Type**:
- [√ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

win11，可能是最新版

**Comment by Vixea** [comment]
Hello, could you please rewrite your message in English and I'll be more than happy to help

**Comment by fouable** [comment]
> I found that the 19.1.1 version of the screen is abnormal when using, like a Mosaic

**Comment by fouable** [comment]
> Hello, could you please rewrite your message in English and I'll be more than happy to help

18.2.3版本运行会瞬间崩溃，后来我想是不是因为我安装了高于这个版本的其他版本的原因，暂时没有去验证

**Comment by fouable** [comment]
> Hello, could you please rewrite your message in English and I'll be more than happy to help

Version 18.2.3 will crash instantly. Later, I wondered if it was because I installed other versions higher than this version that I did not verify for the time being

**Comment by fouable** [comment]
> Hello, could you please rewrite your message in English and I'll be more than happy to help



> Hello, could you please rewrite your message in English and I'll be more than happy to help

Regarding the environment: This issue has been found on a 1650 desktop PC and a 3060 laptop, with the SteamVR version being the latest

**Comment by fouable** [comment]
> Hello, could you please rewrite your message in English and I'll be more than happy to help

About the environment: The issue was found on a 1650 desktop and a 3060 laptop, where the SteamVR version is the latest and the VR device is Meta Quest 2

**Comment by fouable** [comment]
> Hello, could you please rewrite your message in English and I'll be more than happy to help

I used the translation software to translate my question. I'm sorry if you seem confused. Thank you very much for your help!

**Comment by Vixea** [comment]
what about v20?

**Comment by fouable** [comment]
> what about v20?

I cannot give you an accurate answer on version 20. About this version, I was teaching one of my friends to use this pushing tool, and he gave me feedback about the above picture

**Comment by Vixea** [comment]
could i see a picture on the issue on v19

**Comment by fouable** [comment]
> could i see a picture on the issue on v19

I should think so! But I have other things now, please wait for a moment, I will reinstall the version 19 to get the picture of this problem

**Comment by fouable** [comment]
> could i see a picture on the issue on v19

I recently had a request to use the Air Link in Quest 2, but maybe my firmware version was too old to use, so I updated my device, and after the update, I can no longer use any apps from unknown sources, including ALVR

**Comment by fouable** [comment]
> could i see a picture on the issue on v19
The firmware version is V54, and in this version, the unknown source menu is hidden and you cannot see any third-party applications

**Comment by fouable** [comment]
> could i see a picture on the issue on v19

I may never be able to run ALVR on my Quest 2 device again

**Comment by Vixea** [comment]
Did you make sure it didn't get wiped?

**Comment by fouable** [comment]
> Did you make sure it didn't get wiped?

I am sure

**Comment by fouable** [comment]
> Did you make sure it didn't get wiped?

Unless, of course, updating the firmware will automatically uninstall all my apps

**Comment by Vixea** [comment]
Depends my update to v54 wiped it for me so it's possible it did for you

**Comment by fouable** [comment]
> Depends my update to v54 wiped it for me so it's possible it did for you

It's probably not wiped.  Instead, the hardware vendor turned off the unknown source application display

**Comment by fouable** [comment]
> Depends my update to v54 wiped it for me so it's possible it did for you

Hello, for various reasons, today I recorded the latest version of ALVR running on my device

**Comment by fouable** [comment]
> Depends my update to v54 wiped it for me so it's possible it did for you
![Dingtalk_20230628174211](https://github.com/alvr-org/ALVR/assets/62919757/39b27d33-e39b-42a5-add0-d68eebc5089c)

**Comment by Vixea** [comment]
well it looks like its working?

**Comment by fouable** [comment]
> Depends my update to v54 wiped it for me so it's possible it did for you

My ALVR version is 20.1.0, Windows 10 system 1660 graphics card, SteamVR should be the latest version

**Comment by fouable** [comment]
> well it looks like its working?

yes！But it's hard to see

**Comment by fouable** [comment]
> well it looks like its working?

I recorded a video. Do I need to send it to you?

**Comment by Vixea** [comment]
sure why not

**Comment by fouable** [comment]
> sure why not

Sorry, my video is over 10m, I'll record a new one

**Comment by fouable** [comment]
> sure why not


https://github.com/alvr-org/ALVR/assets/62919757/256d49ff-e9d2-4a2b-8270-819a9faeb640

**Comment by ccloli** [comment]
I'm having the same issue since v19, though I resolved it by disabling "Adaptive bitrate", which is the new bitrate algorithm introduced in v19. In v20 you can change "Bitrate" -> "Mode" to traditional "Constant" option.

If you're using v20, you can try scaling down your resolution or bitrate, the default medium resolution in v20 is larger than < v19, so it'll eat more performance.

Also if you're using HEVC, no matter which version of ALVR you're using, make sure the bitrate is under 100Mbps, or your Quest's hardware cannot handle it. The bitrate may depends on your resolution and framerate setting, I'm having glitch and freeze issue with 100% resolution on v19 / Low resolution on v20 when setting to 120Hz + HEVC + 100Mbps. So I'm using H264 and I can go up to 300Mbps.

**Comment by Vixea** [comment]
Some of this information is slightly out of date, but I don't have time right now to correct the out of date bits

**Comment by ccloli** [comment]
> Also the lack of quality smells like out of date configuration of ALVR don't worry I also have been guilty of using out of date information to guide my settings. Could I see your settings.json file?

**Not the OP** and did a quick test just now, but cannot reproduce the issue now. 🤔

The only thing I can see is in v19.1.0, if you enabled Adaptive bitrate, once the game is loading (starting game or loading scenes etc), the video will become blurry for a few seconds. And if you're using HEVC, after game loading, the video quality will become significantly worse, everything is blurry, and never go back to the normal quality.

[Here](https://github.com/alvr-org/ALVR/files/11929698/session.zip) is my config file for v19.1.0.

...though I don't think you need it, cause I don't see the issue in v20.0.0. The blurry problem mentioned before is gone in v20, the video quality is stable before and after game loading (and significately better than v19). And I found the reason I gave up v20 is that the controllers will lose tracking for a while once game loading, but that's another issue.

Instead, in v20.0.0, if I use HEVC with Adaptive bitrate, the video will become glitch and freeze. From the statistics, it's because the client decode takes too much time (around 200ms), maybe it's because the bitrate is too high and Quest cannot handle it.

[Here](https://github.com/alvr-org/ALVR/files/11929710/session.zip) is my config file for v20.0.0.

***

Note again: I'm not the OP, so I recommend @fouable posting your `session.json` file located under ALVR executable folder (maybe a screenshot of statistic panel to determine what's going on).

@fouable 可以发一下 `session.json` 文件，位于 ALVR 的可执行文件目录下，方便开发者排查问题。你可能需要压缩为 zip 文件，因为 GitHub 似乎不支持直接上传 json 文件。如果可以的话，也可以发一下出现问题时「状态信息」面板的截图。

**Comment by Vixea** [comment]
what are you PC's specs?

**Comment by ccloli** [comment]
> what are you PC's specs?

Windows 10 21H2, Ryzen 7 5800X, RTX 3080 (driver 536.40), SteamVR 1.25.8, stream over a wireless router with WiFi-6 160MHz.

**Comment by Vixea** [comment]
without foveated rendering your encoder is not going to be having a fun time until sliced encoding/decoding is implemented(default settings shouldn't be that bad now), 0-0 max_buffering_frames please leave that at default that's all that needs to be said

**Comment by ccloli** [comment]
> without foveated rendering your encoder is not going to be having a fun time until sliced encoding/decoding is implemented(default settings shouldn't be that bad now)

Yep I know that, but I do notice the blurry stuff, so I disabled it and I don't see it kills my GPU or Quest with constant bitrate.

> 0-0 max_buffering_frames please leave that at default

From the GUI it says 1 frame, but I revert to the default 1.5 frames in v20 and don't see any difference with HEVC. Enabling foveated rendering at the same time doesn't work, too.

Everything works fine even not revert these two settings with H.264 (yes, H.264 works fine with constant bitrate and adaptive bitrate, just the lose tracking issue when PC is under heavy load). Pretty sure it's because Quest is unhappy with HEVC + 120Hz, maybe upgrading to v55 may fix the issue. 🤔

**Comment by Vixea** [comment]
could you try manually editing it to 1.5 while the server is closed

**Comment by ccloli** [comment]
> could you try manually editing it to 1.5 while the server is closed

Somewhat it fixed, but it's still glitch when the client connects to the server. From statistic panel, the problem is client side decode. The "fixed" is that once you wait for a few minutes, it will back to normal. 

> wdym enabling foveated rendering at the same time doesn't work

Enable both foveated rendering and resetting max buffering frames doesn't fix the glitch with HEVC.

I upload the video if you want to see, should be valid for around 7 days. I forgot to record the statistic panel (I do think a transparent statistic panel on client side is a good feature), but I'm sure the glitch is because client side decoder is unhappy.

- [Video](https://objectstorage.ap-tokyo-1.oraclecloud.com/p/n5-ll3l5LbdpBuTaoHlhPgbzymocWcvzAyC7XPuCKKW-QDJEDmuescv7uz3NPBb2/n/nrzblovvku9x/b/bucket-ccloli/o/com.oculus.shellenv-20230702-231147.mp4) with game playing, once it connects to the server, the stream is glitch already, and statistic panel shows the decoder takes ~90ms. But the glitch become less, and around 2 minutes, the glitch is gone. Also you can see when the game is loading, the controller is fixed at waist, after a while the controller become trackable.
- [Video](https://objectstorage.ap-tokyo-1.oraclecloud.com/p/nZ5drmTGIDvrriL_GgYUTDmdFo3w7_O5_hjYFw2nAYUTLS2J_vVjdObmvzD-uVab/n/nrzblovvku9x/b/bucket-ccloli/o/com.oculus.shellenv-20230702-231757.mp4) with reconnection to the server, a reconnection will reproduce the glitch.

**Comment by Vixea** [comment]
Your decoder latency overstep I think is using an outdated value

**Comment by Vixea** [comment]
nevermind, try setting 
```
"ConstantMbps": 300,
```
under mode to something around 128

**Comment by ccloli** [comment]
> try setting
> 
> ```
> "ConstantMbps": 300,
> ```
> 
> under mode to something around 128

And... no, it doesn't work. Switching to constant bitrate and set to 100Mbps is fine, but switching back to adaptive bitrate, it still go up to 300Mbps and start glitching.

[Video](https://objectstorage.ap-tokyo-1.oraclecloud.com/p/y0MzC3EbfQ4owN7wpqSwRrjQJhB8XmtMPRuif4abl1fqn9Z9nMKwrmW4Yr4Fy1Mn/n/nrzblovvku9x/b/bucket-ccloli/o/alvr.client-20230703-011750.mp4)

But like what I guessed before, if I enabled "Maximum bitrate" and set to 100Mbps, it become normal.

[Video](https://objectstorage.ap-tokyo-1.oraclecloud.com/p/5y7J2NCcG33p6KGNYmqFSVzB3xef6B_TzvLWTNSMHnP-ORxVXYL-nkk3zB-laxbN/n/nrzblovvku9x/b/bucket-ccloli/o/alvr.client-20230703-011915.mp4)

**Comment by fouable** [comment]
[session.zip](https://github.com/alvr-org/ALVR/files/11932003/session.zip)

**Comment by fouable** [comment]
sorry，I couldn't get this file in the last two days

**Comment by fouable** [comment]
[session.zip](https://github.com/alvr-org/ALVR/files/11932095/session.zip)

**Comment by Vixea** [comment]
Please set your revolution preset to medium, refresh rate should the preset that's higher than the one that's 60hz anyone works, re-enable foveated rendering reset to default if you still think it's too simmery increase the to by .5 buy don't go above .6, and try avoid video glitch

**Comment by fouable** [comment]
> Please set your revolution preset to medium, refresh rate should the preset that's higher than the one that's 60hz anyone works, re-enable foveated rendering reset to default if you still think it's too simmery increase the to by .5 buy don't go above .6, and try avoid video glitch

Ok, I will test according to the Settings you mentioned later

**Comment by ccloli** [comment]
Not the developer, you can try the developer's suggestion first. But if it doesn't work for you, from my experience, try switching protocol from UDP to TCP. UDP has been optimized since v19, but everyone's physical network configuration is various, maybe your router is not ready for many large UDP packets. 

Also a screenshot of statistics panel, a log file or screenshot of log panel may help to diagnose. And since I talked about wireless router just now, what's your wireless router and are you using WiFi 5 or 6 (802.11 ac/ax)? Are you in a place with many wireless devices taking 5G channel? Or since you mentioned you're using a laptop, are you using the wireless interface as an AP? I heard that the hotspot feature comes with Windows doesn't play a good role with wireless streaming, it may laggy and drop packages.

**Comment by fouable** [comment]
ok，I'll try to change the transport protocol，About channel，It is a mixed channel of 2.4g and 5g， i am a vr application developer, in the company，There are a lot of wireless devices out there，I did not use a wireless card to open the hotspot, is a wireless router，thanks for help

**Comment by fouable** [comment]
I changed the bit rate mode to a constant, the value is set at a little more than 100, and the screen performance seems normal!

**Comment by Vixea** [comment]
Ok is the issue your having all resolved?

**Comment by fouable** [comment]
> Ok is the issue your having all resolved?

 yes ，But now I have to set the Bitrate above 200M to feel that the picture is good, but my hardware equipment seems to be unable to bear it；

**Comment by fouable** [comment]
请问您知道20版本什么时候有中文版本吗

**Comment by fouable** [comment]
> Ok is the issue your having all resolved?

Do you know when the Chinese version of version 20 will be available？

**Comment by fouable** [comment]
> Ok is the issue your having all resolved?

Thank you very much for your help!

**Comment by Vixea** [comment]
> > Ok is the issue your having all resolved?
> 
> Do you know when the Chinese version of version 20 will be available？

We do not plan on having translations the only way it makes sense is to have dedicated translators that will stick around and for changes in the project to slow down.

**Comment by fouable** [comment]
Today, I replaced a router for dedicated streaming, the performance is very good, my problems are solved!




&nbsp;


梦若有情便相璃
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月4日(星期二) 下午5:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alvr-org/ALVR] 关于18.2.3APK版本运行闪退与19.1.1和20.0.0版本使用时串流画面模糊，马赛克的问题 (Issue #1668)





   
好的，问题已经全部解决了吗？
  
你知道中文版20什么时候上市吗？
  
我们不打算进行翻译，唯一有意义的方法是拥有专门的翻译人员，他们会留下来，并减缓项目中的变化。
 
-
 直接回复此电子邮件，在 GitHub 上查看或取消订阅。
您收到此消息是因为您被提及。Message ID: ***@***.***&gt;

**Comment by ccloli** [comment]
> Ok is the issue your having all resolved?

For me, sort of, since I've already sticked to constant bitrate and it works fine. Some other issues I mentioned before are off-topic, I'd like to open a new issue if it still presists in latest version.

**Comment by fouable** [comment]
yes！
&nbsp;


梦若有情便相璃
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月4日(星期二) 晚上9:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alvr-org/ALVR] 关于18.2.3APK版本运行闪退与19.1.1和20.0.0版本使用时串流画面模糊，马赛克的问题 (Issue #1668)





  
好的，问题已经全部解决了吗？
  
对我来说，有点，因为我已经坚持恒定比特率并且它工作正常。我之前提到的其他一些问题是题外话，如果它在最新版本中仍然有效，我想打开一个新问题。
 
-
 直接回复此电子邮件，在 GitHub 上查看或取消订阅。
您收到此消息是因为您被提及。Message ID: ***@***.***&gt;
