### ISSUE TITLE
ALVR doesn't start up

### ISSUE THREAD

**Issue by Emoflia** [alvr-org/ALVR#1679]
## Description
When I start ALVR nothing appears and opens, but when I open steamVR separately it writes: "some add-ons are blocked" (alvr server, gamepad support) trying to unblock them doesn't lead to anything. (maybe addons are blocked because of old versions of ALVR)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Installation

**ALVR Version**:from 20.0.0 to 21 (nightly)

**SteamVR Version**:1.26.3

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version**: Windows 10 21H2

**Comment by sv-hmelevsky** [comment]
Hi friend! I have the same problem with Pico 4. Constantly blocked extensions. I don't know how, but Steam stopped blocking extensions, after installing **msi** ALVR version. Also in Installation section I uninstalled all versions of ALVR except current one:

![image](https://github.com/alvr-org/ALVR/assets/4187388/d4698f38-e74d-4e80-9b50-ee3abeb76ca2)

The rules for the Firewall had to be set manually because I got a message when I tried to install it:
![image](https://github.com/alvr-org/ALVR/assets/4187388/5b917a8b-b59d-427b-817a-694415c23085)

Next. I start ALVR on PC with admin rights (just in case). I start ALVR on Pico 4. 
I see that ALVR on PC has detected the device. 
I press Launch SteamVR, I see that the connection status is - **Connected**. 
Then image in the helmet becomes black for a while, as if something is starting and that's it... 
SteamVR gives a message (**Failed** - **No license**):

![image](https://github.com/alvr-org/ALVR/assets/4187388/8e500991-d31e-423f-8def-453ef5d268fa)
That's all, any VR game that I run, runs only on PC, not on the Pico 4

**Comment by Emoflia** [comment]
After I deleted absolutely all files related to ALVR, the problem with addons went away - but ALVR still won't start. No matter how I installed it, the result is the same: after installing the application just doesn't start. On startup I can see for one second a "Windows error report" appearing in the task manager.
![image](https://github.com/alvr-org/ALVR/assets/104817815/9c0aeaaf-0a3d-41dc-96c6-04e8dff879a1)
I can try to install the old version, but I think the problem with addons will come back.

**Comment by Vixea** [comment]
please don't use steamVR nightly right now

**Comment by sv-hmelevsky** [comment]
CPU: Ryzen 7 5800X3D
GPU: RTX 4090
OS: Win 10

**Comment by Vixea** [comment]
Hmelevsky yours sounds like a different issue try verifying SteamVR

**Comment by sv-hmelevsky** [comment]
> Hmelevsky yours sounds like a different issue try verifying SteamVR

I have no problem playing any VR game via Virtual Desktop. 
The only problem I have is with ALVR. :\
P.S. I wanted to try another way of streaming (instead of VD) and compare the quality.

**Comment by Vixea** [comment]
could you translate the popup on the side in your original post?

**Comment by sv-hmelevsky** [comment]
> could you translate the popup on the side in your original post?
Yes, sure!
**Failure** 
no license

This is the first time I have received this error.

**Comment by Vixea** [comment]
It's possibly because you have VD's addon still enabled or something with VD

**Comment by Vixea** [comment]
@sv-hmelevsky any luck?
