### ISSUE TITLE
Some questions I'd like to discuss with you about resolution and frame rate

### ISSUE THREAD

**Issue by Hope10086** [alvr-org/ALVR#1746]
First of all, may I ask the default setting of the monocular resolution height is always larger than the width of this setting is what basis? Why isn't it a square? 

Secondly，the client frame rate displayed on the statistics panel does not seem to be precise.The device I use is Meta quest Pro which supports 72Hz and 90Hz tracking frequencies.The client decoder is saturated when I set a higher resolution (such as 5184*2848) and a 90Hz tracking frequency. At this point, the server can produce a 90fps video stream, but the client has selectively discarded some video packets when decoding, so the actual client frame rate must not reach 90fps. Of course, I have not had time to carefully understand the source code here.

**Comment by zarik5** [comment]
> First of all, may I ask the default setting of the monocular resolution height is always larger than the width of this setting is what basis? Why isn't it a square?

It depends on the preferred aspect ratio of the VR runtime for its swapchains. We could actually decide to use a different aspect ratio, but that will cause pixels to not be squares (unless we also tweak the field of view accordingly).

As for the client FPS, it's accurate, but it's not the client refreshrate, it's the frame of new frames submission. If the server is generating frames at 90fps, but the client fps drops, it means the client is discarding frames. This is because the pace of frames was uneven. To fix this we would need to properly implement a frame queue with phase sync, or for now you can just increase "Maximum buffering".

**Comment by Hope10086** [comment]
Thank you very much.
