### ISSUE TITLE
Disable User entitlement check for offline PICO check

### ISSUE THREAD

**Issue by GetTuh** [alvr-org/ALVR#1777]
When launching the app on PICO devices it does so called **User entitlement check**. Unfortunately the default is to kill the app, so it's booting user off after a minute or so after using it if he doesn't have internet connection. 

Following the official documentation on https://developer-global.pico-interactive.com/document/unity/user-entitlement-check/  it seems like either passing the check and doing nothing or setting the kill to false would resolve this problem. 
User reported in  #1743

**Comment by galister** [comment]
ALVR does not use the Pico Unity/Unreal SDK, it uses standard OpenXR, which has no way for enabling or disabling entitlement checks. And so you can bet that we're not enabling any.

That being said, I'm also getting this ever since my Pico 4 updated to 5.7.0 this weekend. I purged and re-installed the same exact APK that worked before and now it's giving me this entitlement error.

My Pico has not been on the internet for 3+ months, I even upgrade it offline. ALVR has worked without any issues before this update.

This leads me to believe that the Pico system version 5.7.0 introduced this bug. I'm going to voice my concerns to Pico and I urge you to do the same.

**Comment by GetTuh** [comment]
Right, I got that error on 5.6.0 . Let's pray its really a bug and not PICO doing something shady.

**Comment by Meister1593** [comment]
> ALVR does not use the Pico Unity/Unreal SDK, it uses standard OpenXR, which has no way for enabling or disabling entitlement checks. And so you can bet that we're not enabling any.
> 
> That being said, I'm also getting this ever since my Pico 4 updated to 5.7.0 this weekend. I purged and re-installed the same exact APK that worked before and now it's giving me this entitlement error.
> 
> My Pico has not been on the internet for 3+ months, I even upgrade it offline. ALVR has worked without any issues before this update.
> 
> This leads me to believe that the Pico system version 5.7.0 introduced this bug. I'm going to voice my concerns to Pico and I urge you to do the same.

Interestingly, i'm on 5.7.1 beta china and i don't seem to have this issue?
