### ISSUE TITLE
handshake error

### ISSUE THREAD

**Issue by FRANKLIM233** [alvr-org/ALVR#1785]
error while waiting for stream ack

**Comment by OolooOtsoop** [comment]
also getting handshake error. 

here is the exact error I'm getting

Error  Handshake error for (my device hostname): Error while waiting for stream ack: Timeout disabled backtrace

ALVR worked once before just after i installed the alvr-git package from the aur but has since stopped working. I have also tried using the pre-built packages from the releases tab still didn't work. Tested versions are latest stable and the latest 2 nightly versions. 

I tried running it on my home router and my dedicated router to test if it was my router failing but it seems like they both do not work.

**Comment by FRANKLIM233** [comment]
> also getting handshake error.
> 
> here is the exact error I'm getting
> 
> Error Handshake error for (my device hostname): Error while waiting for stream ack: Timeout disabled backtrace
> 
> ALVR worked once before just after i installed the alvr-git package from the aur but has since stopped working. I have also tried using the pre-built packages from the releases tab still didn't work. Tested versions are latest stable and the latest 2 nightly versions.
> 
> I tried running it on my home router and my dedicated router to test if it was my router failing but it seems like they both do not work.
> 
> edit: I tried using the latest dev build on windows using the installer and had the exact same issue as on linux. works once after install and every proceeding use after quitting out and opening again something breaks.

  Just found ALXR18.4.0 working well

**Comment by OolooOtsoop** [comment]
just got to try the latest dev build (ALVR v21.0.0-dev00+nightly.2023.08.20) and it works well. the graphs are broken and the software doesn't appear to recognize that a headset is connected but it looks like it's just a visual bug. otherwise works flawlessly on linux/ pico4
