### ISSUE TITLE
About openxr extensions

### ISSUE THREAD

**Issue by WuZemyp** [alvr-org/ALVR#1858]
Hello, I am recently focusing on getting the dynamic foveation center during the video streaming. After I get the permission in quest pro, I got the data from ALVR. I saw that the openxr extension you used is {fb_eye_tracking_social}, but this one doesn't provide the foveation center of the eye in the frame. So I would like to try another one called {XR_META_foveation_eye_tracked}. I am not familiar with rust and I have checked the openxr in rust, it seems I can't directly call the function in this extension. Would l ask the openxrs lib you used in alvr is implemented by yourself ? Is there any methods to use this extension in alvr code?
Thank you in advance!

**Comment by zarik5** [comment]
XR_META_foveation_eye_tracked seems to be for applying foveation inside the swapchain. if you want to apply foveation for the video streaming you have to calculate the center yourself using a bit of trigonometry.
The library openxrs is not written by me. I forked it since it was not getting updated fast enough, and I'm considering removing it completely and make my own bindings from C headers.
Anyway, we would like to have both eye-tracked swapchain foveation and video encoding foveation. If you want to help, the first thing to do is figuring out why fixed clientside foveation does not work. This should be enabled with XR_FB_foveation but it doesn't work. This extension is required by XR_META_foveation_eye_tracked so we have to fix this anyway first.

**Comment by WuZemyp** [comment]
Thank you for your reply! I can get the eye orientation and position from the extention {fb_eye_tracking_social}. But this one in the official documentation said, is only suitable for avatars eye social. So even if I can calculate the center by myself, this data is not good. Because they filter lots of data in this extention. The problem you talked about I think is caused by permission?[https://mbucchia.github.io/OpenXR-Toolkit/et.html#considerations-for-quest-pro](url), you may have a look at this page,Considerations for Quest Pro. I am not sure whether it is caused by the type of runtime. But if XR_FB_foveation can not be enabled, how you enable  {fb_eye_tracking_social}. I think XR_FB_foveation is a pre-request of fb_eye_tracking_social.

**Comment by WuZemyp** [comment]
By the way, for the openxr in rust. I have found GetFoveationEyeTrackedStateMETA this function in generated.rs. But it is just a function pointer, how can I call this function?

**Comment by WuZemyp** [comment]
Could I ask the eye_tracking_social.rs is also not written by you right? If I want to add some code or modified some code in that file, or we say in that code scope. How can I do that? I want to imple XR_META_foveation_eye_tracked for Session, I saw the code in eye_tracking_social.rs, I just want to do the same things. If I modified local, it seems doesn't work. Thank you in advance!
