### ISSUE TITLE
Linux: Unable to load driver alvr_server... libx264.so.164: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by josbraden** [alvr-org/ALVR#2130]
## Description

SteamVR doesn't load alvr driver, error logs in vrserver.txt says:

```
Wed May 15 2024 16:17:14.312120 [Info] - Unable to load driver alvr_server from /home/josh/git/ALVR/build/alvr_streamer_linux/lib64/alvr/bin/linux64/driver_alvr_server.so (libx264.so.164: cannot open shared object file: No such file or directory)
Wed May 15 2024 16:17:14.312137 [Error] - ASSERT: "DriverManager alvr_server load error libx264.so.164: cannot open shared object file: No such file or directoryu" at /data/src/common/vrcommon/drivermanager.cpp:439.
Wed May 15 2024 16:17:14.312153 [Error] - Unable to load driver alvr_server because of error VRInitError_Init_FileNotFound(103). Skipping.
```

## Workaround

Copying `libx264.so.164` from `/usr/lib/x86_64-linux-gnu/libx264.so.164` to `/home/josh/git/ALVR/build/alvr_streamer_linux/lib64/alvr/bin/linux64/` allowed the driver to load

## General Troubleshooting
- [x ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x ] I read the ALVR Wikis [polygraphene's ALVR GitHub Wiki](https://github.com/polygraphene/ALVR/wiki) and [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware

https://linux-hardware.org/?probe=ef089331bd

### Installation

**ALVR Version**: v21.0.0-dev01

**ALVR Settings File**:

**SteamVR Version**: 2.5.5

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Ubuntu 24.04 LTS

**Comment by mohammad-matini** [comment]
Started facing the same issue on linux[1] today, with ALVR v20.8.1, and SteamVR current, beta, and previous.  The only thing I suspect changed since last working run is the SteamVR build, but I'm not sure.  Checking SteamVR logs is helpful as Josh mentioned, also, maybe check:
```
ldd ALVR/build/alvr_streamer_linux/lib64/alvr/bin/linux64/driver_alvr_server.so
```
For me, it shows:
```
$ ldd driver_alvr_server.so
        [...]
        libx264.so.163 => /usr/lib64/libx264.so.163 (0x00007f7d7bea3000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f7d7be82000)
        libasound.so.2 => /usr/lib64/libasound.so.2 (0x00007f7d7bd7d000)
        [...]
```
Notice it's linked against _libx264.so.163_ in my case, and not _libx264.so.164_.  Same work-around as Josh mentioned, put the appropriate version of the shared library in `ALVR/build/alvr_streamer_linux/lib64/alvr/bin/linux64/`.  For me, it allows the ALVR server to start now, but I still get a black screen in the headset.  Warning about invalid playspace size in ALVR Dashboard.  Many messages in the SteamVR logs, but I haven't untangled them yet.  Will investigate a bit more...

[1]: Slackware 15 with a lot of custom packages and rebuilds.

**Comment by josbraden** [comment]
@mohammad-matini I'm also getting the black screen after encountering this issue, but was unsure if that was related

**Comment by mohammad-matini** [comment]
Compiling with --gpl is also a work-around for the x264 issue, because it statically embeds it instead of dynamically linking it.  Still no luck with the black screens though.  I don't have a good debugging workflow yet.  Attaching GDB randomly is not helping much.  Also, GPU is integrated AMD, but not on a laptop.
```
Mesa Gallium driver 23.1.3 for AMD Radeon Graphics (renoir, LLVM 13.0.0, DRM 3.42, 5.15.94)
```
```
30:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] (rev c9)
```

**Comment by mohammad-matini** [comment]
@josbraden Install https://github.com/Scrumplex/Steam-Play-None, use it to force Steam to not use a container when running SteamVR.  I now have video on the headset again.

**Comment by mohammad-matini** [comment]
@josbraden Do you think this should be closed?  The issue with the x264 library is a discrepancy between our build environments and the Steam runtime.  The official ALVR builds statically link x264, so they don't have this problem.  I see nothing the ALVR project could do about this for now, other than maybe clarifying why you might want the --gpl option on the Wiki or something, or adding instructions about compiling ALVR inside Steam runtime containers.

**Comment by josbraden** [comment]
Agreed, thanks for tracking this down!

**Comment by ztx-lyghters** [comment]
> @josbraden Install https://github.com/Scrumplex/Steam-Play-None, use it to force Steam to not use a container when running SteamVR. I now have video on the headset again. Some weird interaction between SteamVR's runtime container and the Vulkan layer.

How did you even made it work? I'm getting this error, while trying to run SteamVR with Steam-Play-None:
`vrstartup.sh[28909]: ERROR: no steam runtime environment set, please use sniper SLR`

**Comment by ztx-lyghters** [comment]
I've managed to bypass this error by commenting a few lines in the 'vrstartup.sh' script like so:

`$HOME/.local/share/Steam/steamapps/common/SteamVR/bin/vrstartup.sh`
```sh
#if [ -n "${PRESSURE_VESSEL_RUNTIME-}" ]; then
#	log "Steam Linux Runtime: ${PRESSURE_VESSEL_RUNTIME}"
	logger="$(which srt-logger)"
#else
#	log "ERROR: no steam runtime environment set, please use sniper SLR"
#	exit 1
#fi
```

Be sure to notice that line `logger="$(which srt-logger)"` was not commented out. Hope that'll have anyone in the future.
