### ISSUE TITLE
Hardware encoding isnt supported while its on my gpu

### ISSUE THREAD

**Issue by Lucideds** [alvr-org/ALVR#2156]
## Description
Whenever I launch SteamVR through alvr i get both errors:
```txt
19:43:53.690503678 ERROR H264 profile does not contain encoding entrypoint. You unlikely to have hardware encoding for it.` 
19:43:53.690507284 ERROR HEVC profile does not contain encoding entrypoint. You unlikely to have hardware encoding for it. 
``` 
Even though I have both of these requirements on my 3060 laptop card  
This is what i got using the "ffmpeg -encoders | grep nvenc" cmd
```txt
 V....D h264_nvenc           NVIDIA NVENC H.264 encoder (codec h264)
 V..... nvenc                NVIDIA NVENC H.264 encoder (codec h264)
 V..... nvenc_h264           NVIDIA NVENC H.264 encoder (codec h264)
 V..... nvenc_hevc           NVIDIA NVENC hevc encoder (codec hevc)
 V....D hevc_nvenc           NVIDIA NVENC hevc encoder (codec hevc)
```

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [polygraphene's ALVR GitHub Wiki](https://github.com/polygraphene/ALVR/wiki) and [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
https://linux-hardware.org/?probe=b7a6d5af96

### Installation
**ALVR Version**:
20.8.1
**ALVR Settings File**:
default settings
**SteamVR Version**:
latest
**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`) *i am using the .tar.gz for linux*
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Pop!_OS 22.04 LTS

**Comment by dyargici** [comment]
I have exactly the same issue with identical versions of everything (SteamVR, ALVR, Pop!_OS 22.04 LTS) only difference being I have a NVIDIA GeForce RTX 3050 (6GB).

I have been Googling like crazy over the last 24hours because I think it related to this (vainfo output):

`libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit`

**Comment by damaestro** [comment]
Hardware encoding for nvidia is not supported via VA-API. https://github.com/alvr-org/ALVR/wiki/FFmpeg-Hardware-Encoding-Testing#nvidia-gpu

Quickly looking at the hardware, it's possible that the Intel graphics is attempted to be used instead of the nvidia GPU. Please review https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting#amdintel-integrated-gpu--nvidia-discrete-gpu

**Comment by dyargici** [comment]
OK, thank you for the help and for the clarification.  I should add that the only reason I'm faffing with all this is because I get nothing but a black screen from ALVR (although I can also see the Quest 2's boundary through the headset).  I'd be happy to mess around trying to find optimal encoder settings etc. however currently I just see black.

**Comment by The-personified-devil** [comment]
This is a known issue with newer SteamVR versions, see https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting for a fix

**Comment by dyargici** [comment]
Thanks again.  I believe you are referring to this:

`Fix

Add ~/.steam/steam/steamapps/common/SteamVR/bin/vrmonitor.sh %command% to the commandline options of SteamVR.

The path might differ based on your installation of Steam, for example on systems using the deb-package like Debian and Mint ~/.steam/debian-installation/steamapps/common/SteamVR/bin/vrmonitor.sh %command% is needed.`

I have tried both paths (using the ~ and also explicit /home/... path as I read somewhere that it might need to be explicit - no idea why that would be...).  I am running Pop!_OS, which is debian based.

I'm quite new to Steam, I assume that when the help says "add to the commandline options of SteamVR" it's referring to right-clicking the SteamVR launcher in Steam then Properties -> General -> Launch Options?

Thanks again for your help, I'm happy to take this over to Discord if that is more appropriate.

**Comment by The-personified-devil** [comment]
> I'm quite new to Steam, I assume that when the help says "add to the commandline options of SteamVR" it's referring to right-clicking the SteamVR launcher in Steam then Properties -> General -> Launch Options?

yes exactly, I'll have to admit might've not worded that the best in the wiki

**Comment by dyargici** [comment]
Thanks.

OK, well I think I've now tried everything I can find online and through searching the Discord and issues here on GitHub.  Kinda at a loss. :/

I'm running wired, I have a very high quality cable, I am set to TCP, I have the adbforwarder working without issue, I can launch the apk on the headset everything says it's connected and streaming, I have no errors reported by ALVR.

The only odd thing I see is this error from SteamVR:

`Headset error make sure your headset's display is in fullscreen mode error -202`

...and the fact that SteamVR peppers my workspace with empty un-killable windows with every attempt.

Think I'm gonna call it and cut my losses unless there is anything else you might suggest?

**Comment by kmare** [comment]
@dyargici I had to downgrade steamvr version in order to get it to work. 
To do that, go to steamvr (from the steam app) -> betas and select previous version. Restart and it should work.
