### ISSUE TITLE
ALVR for SLR3.0

### ISSUE THREAD

**Issue by saikuru0** [alvr-org/ALVR#2190]
This is less of an issue and more of a plea for help. Steam rolled out an update for SteamVR like a day ago, now it's at 2.6, "previous version beta" is now 2.5.5, and the 2.4.4 version, the last one to work with ALVR (only with Steam-play-none compatibility, too) , got put behind an inaccessible, password-protected branch as seen on steamdb. I'd love to get ALVR working on Steam Linux Runtime 3.0 (sniper), and at least on the currently oldest available 2.5.5 version of SteamVR - I can't tell if I'm doing something wrong on my side.

**Comment by Vixea** [comment]
https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting
Also it's physically impossible to build alvr with any SLR version rn because of the layer.

**Comment by The-personified-devil** [comment]
The issue causing the current trouble isn't SLR 3, it's that the vrcompositor component of SteamVR is ran in SLR 1, which means we would have to build the vulkan layer for SLR 1, which we can't do. This is something that will be fixed by not having the layer, i.e. direct mode support. Otherwise SLR isn't really needed, it works without it, it would simply provide a minor amount of additional stability guarantees. This is something I'd do as a CI only thing, since it'd only be wrapping existing build steps.
Closing in favor of #2165
