### ISSUE TITLE
[Feature request]Is it possible to map the Quest VR controllers as trackers and use hand tracking as the controllers?

### ISSUE THREAD

**Issue by 979500318** [alvr-org/ALVR#2322]
Is it possible to map the Quest VR controllers as trackers and use hand tracking as the controllers?

Like this:https://x.com/i/status/1791187692094447997

(gpt translation)

**Comment by The-personified-devil** [comment]
Seems kinda useless, because nearly all wireless vr headsets have camera-based tracking (and if you have base-station tracking then that already works with steamvr with alvr). This means that it's incredibly easy for your feet to go out of the field of view of the cameras and for your feet to loose tracking. If you pr this it might get merged, since it might be useful for other things, but otherwise this is not planned

**Comment by zarik5** [comment]
@979500318 like the author says in the post comments, the video is fake. Because Meta hasn't provided a suitable API to make it possible, so we cannot do it either. it doesn't mean the hardware forbids it, actually Meta already has a api to track controllers and fingers at the same time, but only when the controllers are in the hands.

**Comment by 979500318** [comment]
> @979500318 like the author says in the post comments, the video is fake. Because Meta hasn't provided a suitable API to make it possible, so we cannot do it either. it doesn't mean the hardware forbids it, actually Meta already has a api to track controllers and fingers at the same time, but only when the controllers are in the hands.

So it's a fake? That's a shame. Thanks.

**Comment by zarik5** [comment]
I want to implement concurrent tracking of controllers and hand skeleton rather soon, so we can see how it behaves then.
