### ISSUE TITLE
Add back Windows 7 support

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#247]
After the encoder and compositor rewrite, switch from RGB to NV12 texture format

**Comment by uq1** [comment]
Please do this. Windows 10 is the most unbearable piece of malware ever created.

**Comment by VykosX** [comment]
Seconding this with all my heart. Please readd this option that makes ALVR compatible with Windows 7 again. I'm sick of dual booting to Windows 10 just to use VR when Windows 7 is better by a mile and you have to jump through so many hoops to do basic things on Windows 10.

ALVR v11 works perfectly on my Quest but it's a shame to be missing out on newer features and better performance because NV12 is missing from the newer versions. Please, on behalf of so many people who still daily drive Windows 7, please readd support for this option. Many thanks.

**Comment by IssacDowling** [comment]
More support is better, and if you like windows 7, fair enough, but many modern things just don't care anymore. Even if ALVR re-added support, it's likely lots of other important things will become too out-of-date to be reasonable sometime soon

**Comment by VykosX** [comment]
That's all well and good but the thing is most of these limitations are downright artificial. There's little reason why Windows 7 can't be supported for the entire VR ecosystem even if it might require a workaround or two. SteamVR works perfectly fine and so does Vive software. Oculus was the one who dropped support for no good reason other than to force people to migrate and to forcefully consolidate their platform, just like Microsoft did when they kept DirectX 12 and Mixed Reality as Windows 10 exclusives.

If at all possible to re-introduce support for Windows 7, me and many others would be extremely grateful. As it is, ALVR is currently the only way to experience VR with Oculus headsets for this system, since Virtual Desktop relies on APIs that do not work and they refuse to add support for GDI capture, and the Oculus Software explicitly phones home to Facebook every 30 seconds and bricks your setup when it detects you're not running Windows 10 (even though it otherwise would work just fine).

In the time being ALVR v11 works acceptably in Windows 7 but it's missing a lot of performance improvements and features as well as support for the Quest 2. We're not asking for extended support and perhaps a day will come when it's truly untenable to maintain, but as it stands this issue is still marked open and from my limited understanding, it merely needs reincorporating some features that were present in the older versions for it to work again.

Perhaps a dev would be capable of explaining in more detail what would be required and how difficult it would be to address this. I wholeheartedly offer my support for this issue to be considered. Thank you.

**Comment by zarik5** [comment]
Windows 7 support was removed because it required CUDA for the build and this was a major hurdle for people that wanted to build from source. We didn't have a Windows 7 machine to test and moving forward removing the support was the easiest thing. We plan to work again on the encoder, this time using the Vulkan video extension; it's still provisional and not yet supported on AMD hardware. Once we are there we can test if it supports Windows 7, but we have to prioritize the later Windows versions.

**Comment by VykosX** [comment]
I see. Would it be possible to re-integrate cuda support into a separate build to readd support in the meantime? Failing that, I will wait for the Vulkan extension, and I'll gladly test any builds you guys might need to ascertain compatibility with Windows 7. Thank you very much for the response and the excellent work on this software!
