### ISSUE TITLE
Map more buttons to handtracking gestures

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#256]
Update: I devised a plan for reliable gestures for button mapping.

Touch gestures are triggered simply by finger curl: "A" touch for thumb, trigger touch for index. Grip is enabled by middle/ring/pinky curl.

Other buttons are activated with a double hand gesture: one hand does a pinching gesture with index+thumb and is the one that receives the button press, the other hand is positioned with open hand or closed fist in some easy to recognize positions that determines the button being clicked. Lastly the joystick can be mapped to X/Z translations to the hand that is pinching.

**Comment by ccloli** [comment]
I noticed the hand pinch feature is removed since v18, though tbh the feature is really frustrating, since it triggers randomly.

Maybe it's possible to use the interaction like Quest's gesture? I mean press specific button when **the hand faces to you** and **you do a hand pinch**, just like what Quest's native support gestures, pinch index + thumb for 1 second with right hand will press Oculus button, and with left hand will press Menu button (though looks like it's disabled in ALVR v19, the button click doesn't work).

I think a possible solution may look like this:

- When you turn your hand and face it to yourself, you're entering button mapping mode
  - Would be cool if there's an overlay over each finger on client side, to show which button will be trigger, like Quest's native Menu button and Oculus button
- Pinch thumb + index: Left: Menu / Right: Oculus (Quest's native feature)
- Pinch thumb + middle: Left: Y / Right: B
- Pinch thumb + ring: Left: X / Right: A
- Pinch thumb + pinky: Click joystick
- Pinch thumb + pinky + ring: Move joystick
  - When doing this pinch, move hand forward/backward/left/right to emulate joystick move
  - Should have a dead zone to prevent shaking
  - Would be nice there's an onverlay on client side to show the dead zone and move area
- Pinch thumb + middle + ring: Scroll trackpad (if emulated as Index controller)
- All these controls can be set with a threshold time in setting panel to prevent trigger accidently

Should consider if it can be done easily since ALVR needs to figure out which finger are pinched. If it's hard, another way is use just single pinch but do all the things, like Oculus button gesture. When you face the hand to you and pinch thumb + middle , an overlay shows on client side, move up/down/left/right to touch / hover on specific button, release finger to press the button, move out fast to cancel the action.

**Comment by zarik5** [comment]
From my experience, hand tracking is not good enough to reliably detect pinches. VRChat gesture scheme on the Quest version relies on hand tracking pinches and it's frustratingly unrealiable. For example the mic gets muted randomly and then it's so hard to unmute. The gesture scheme i put on the OP uses broad, simple and clearly detectable hand gestures.

**Comment by ccloli** [comment]
I think my suggestion would be more ergonomics since it's just like what Quest already have, so it's easy to learn. But I do understand it's hard to detect which finger is pinching, as I tested it just now, the other fingers (especally pinky finger) are hard to pinch in Quest. I noticed there is a PR #1715 is about hand pinching, not sure if it will address this problem.

**Comment by zarik5** [comment]
Hand tracking gestures have been merged.
