### ISSUE TITLE
Extremely high latency

### ISSUE THREAD

**Issue by Derpalus** [alvr-org/ALVR#353]
### Bug reports:

I experience extreme latency in image and audio (mostly in transport it seems). Note however that there is no issue with the transport, pinging the headset gives a reliable 1ms or less. ALVR has also worked perfectly fine for me earlier, but one day something happened and this is the result. The image moves like molasses and it takes several seconds from the head being moved to the image catching up.

I have upgraded both the client and the server since this started happening, didn't do any difference. I have restarted both PC and router several times.

Given that this has worked before but now continues to not work even through updates I'm inclined to think something has been stored somewhere that is interfering.

![image](https://user-images.githubusercontent.com/17323868/99594805-f9393600-29f3-11eb-83fb-7b5d66919b44.png)

#{ "id": "statistics", "content": {"totalPackets": 187617, "packetRate": 1520, "packetsLostTotal": 0, "packetsLostPerSecond": 0, "totalSent": 256, "sentRate": 16.620000, "totalLatency": 4069354.893000, "encodeLatency": 10.094000, "encodeLatencyMax": 21.993000, "transportLatency": 36984.701000, "decodeLatency": 13.371000, "fecPercentage": 10, "fecFailureTotal": 1, "fecFailureInSecond": 0, "clientFPS": 28, "serverFPS": 72} }#

#### Environement

Hardware:
Intel Core i7-4770K
NVidia GTX 1080
Router: Linksys wrt1900acs

ALVR versions tested:
client: 12.0.0, 12.5.0
server: 12.0.0, 12.6.1

Windows version 2004 (so there is potential to update to 20H2)

**Comment by ratozumbi** [comment]
Please respond even if solved the problem.
I don't have the solution but maybe this might help:

I notice this same behavior when opening ALVR, but then it catches up. When playing on my notebook the problem is more prominent and takes longer to sync and the sync might be lost more easily, but it is usually due to some other program consuming resources.

My advice is to close everything else that is running on the background. It might help also if you set the affinity of ALVR server with the non core CPUs (an example on a 4 core CPU is to set ALV server to run only on cores 3 and 4). This can help as there is no concurrency of the server with other processes.

(Side note: I used to own a Lenovo Explorer and the Windows Mixed Reality drivers on my notebook would give me this same issue, so I suspect it is nothing related to ALVR. Although I admit that opening Steam VR Home on top of Windows VR Home worsen the problem drastically)

**Comment by domacikolaci** [comment]
I personally have isolated the issue to having Firefox open while gaming.

For context, most of my job relies on web based applications, so my Firefox consumes alot of my RAM. Now, even though when I game my system is sitting at ~50% RAM usage usually (16GB used out of 32GB of total RAM), for some reason this causes significant lag.

Moment I closed Firefox, lag went and performance was super snappy with 90Hz mode running for the Quest 2.

Im using latest server and apk as of date of this post from the releases section.

**Comment by wizardwatch** [comment]
Firefox could be using hardware encode, decode, or some other hardware acceleration. You might try opening 100 copies of a static webpage to load up ram without using any hardware acceleration to isolate if hardware acceleration is the problem.

**Comment by Derpalus** [comment]
My problem is solved now. There are two things I did.

1. Updated to version 13.2 which seems to connect differently to Steam, but what I really think did it:
2. Disabled Killer Network Manager which is some sort of crap that comes with the motherboard. It apparently was running some sort of "optimization" which I bet was "optimizing" away my network throughput.
