### ISSUE TITLE
Stuck on the message "press 'trust' to continue"

### ISSUE THREAD

**Issue by TheDuck8283** [alvr-org/ALVR#398]
I don't know if this is the place to put this, but I'm trying to use ALVR on my headset and it gets stuck on press "trust" to continue. I've read through the troubleshooting and that didn't help. Tried editing the firewall, no use. Please help!

**Comment by JosNun** [comment]
Hey @TheDuck8283 we'd be glad to help you sort out your connection issues! Because issues like this tend to be a long conversation and involve a lot of debugging, would you mind asking in the \#help channel on the [ALVR Discord?](https://discord.gg/XgVFDtWyrn)? We'll do our best to get you sorted out there. Thanks!
