### ISSUE TITLE
General Questions

### ISSUE THREAD

**Issue by lvilca-tekton** [alvr-org/ALVR#542]
I was wondering about:
1) Is there finger tracking support?
2) How to start this on boot with windows?
3) Why is this not in the oculus store yet? Considering that VD is now plug and play (able to install throught the built in store)

**Comment by zarik5** [comment]
1) Yes. Just put down the controllers.
2) https://support.microsoft.com/en-us/windows/add-an-app-to-run-automatically-at-startup-in-windows-10-150da165-dcd9-7230-517b-cf3c295d89dd
3) ALVR got rejected because it requires non-Oculus software to run (SteamVR). On the other hand for Virtual Desktop, even if it supports SteamVR games, SteamVR is not required because it implements its own VR runtime.

Please do not use GitHub issues for general questions. Use the Discussions tab or ask in the Discord server.
