### ISSUE TITLE
Rainbow artifacts when increasing video resolution - Quest 2

### ISSUE THREAD

**Issue by xcloudx01** [alvr-org/ALVR#574]
I'm unable to increase the video resolution as when I pick something over 100%, I get the following video artifacts:
https://www.youtube.com/watch?v=uTwGrkk0Q-U

Weirdly enough it only occurs inside the headset, it doesn't appear if I record a video using the headset.

#### Environement

What hardware do you have: CPU, GPU, Audio:   cpu - i5-8600k.   gpu - RTX 3090.  Audio - AudioQuest Dragonfly Black
What version of ALVR and SteamVR have you tried:  ALVR server v15.1.0. SteamVR 1.17.3
Windows version: 20H2 (OS Build 19042.867)

**Comment by zarik5** [comment]
I have them too, i think it's the Quest decoder that can't keep up.

**Comment by Pesoen** [comment]
Odd, got a quest 1 and can push it to 125 without issues. Anything higher and it wants h265, but i prefer h264, so i just keep it at 125, got no weird rainbow artifacts, on older hardware as well.

**Comment by Ekristoffe** [comment]
The Quest 1 is 1440 x 1600 (2.3 million pixel)
The Quest 2 is 1832 x 1920 (3.5 million pixel)
As far as I understand maybe the decoder of the quest 1 was able to do more work and the one in the quest 2 is borderline underpowered ...

**Comment by Pesoen** [comment]
except spec wise that would not make sense, the quest two has a chip built for vr, and the quest one had a normal mobile chip in comparison.. sure the decoder might be weaker, but i still doubt that, as it would happen to more things than just alvr streams if that was the case..

but sure, could be the case, even if i doubt it a lot. a simple way to test it is to use a link cable.. it will decode the same, but just do it using a cable instead of wifi, if the rainbow artifacts still appear, it could be a decoder issue, or maybe a defective quest 2. if it stops when using the link cable, the issue is elsewhere, and further testing would be needed.

**Comment by sctanf** [comment]
Link (and VD) use sliced encoding while ALVR does not. Maybe artifacts appear because the decoder is overloaded from a single stream vs. using multiple streams?

**Comment by Firepal** [comment]
Quest 2 user here. I actually get these artifacts in the ALVR grid "waiting area" as well. This makes me wonder if the GPU can't keep up with rendering ALVR at over 100% resolution, because the rainbow tearing affects the Guardian overlay.

Though it is interesting that Oculus VrApi's "Extra Latency Mode" is enabled by default in ALVR, which is supposed to give the GPU more time to render.

**Comment by xcloudx01** [comment]
Interesting. Yeah, it is very strange how when I had the Quest 1, I could easily run it at 125% resolution. So does the Quest 2 use a different video decoder?

**Comment by ronthecookie** [comment]
FYI, we've [had this conversation before](https://discordlogs.jlz.fun/log/570fdb53). ([discord message link](https://discord.com/channels/720612397580025886/720639083616927795/838172493092487239))
