### ISSUE TITLE
Client resolution doesn't match server resolution

### ISSUE THREAD

**Issue by Firepal** [alvr-org/ALVR#648]
On Quest 2, 100% resolution is 1400x1600 per eye instead of 1824x1920, which is what the server renders at.
150% is closer to screen resolution.

<details>
<summary><i>(This part is mostly speculative and based on experience with Quest gamedev)</i></summary>
<br>
I believe the Oculus runtime (or some part of that) transparently resizes the client render target to a lower resolution.<br><br>
My idea is to:<br>
<ul>
<li>divide the client rendertarget width by (the actual per-eye width divided by fake render target width) (1824/1400 on Quest 2)</li>
<li>divide the client rendertarget height by (the actual per-eye height divided by fake render target height) (1920/1600 on Quest 2)</li>
</ul>
which would hypothetically undo the resize. This could be done serverside and sent in the config packet.<br>
The reason to do this would be to make the most of the video sent to the headset.
</details>

**Comment by zarik5** [comment]
100% corresponds to the resolution the headset provides us through the Oculus API. While the resolution provided is not really 100%, we cannot even univocally define what means 100%. 1824x1920 is the screen resolution per eye, but before the image gets rendered on the headset screen, it is distorted by the runtime for lens distortion compensation. This means that if the image  usually fills the screen (except for the corners) this means that the source image must be even larger, and there is no clear method on how to get this exact resolution. But at this point it is not even worth worrying about it since such resolution is too high to be streamed successfully.

**Comment by Firepal** [comment]
OH. Completely forgot about lens distortion, I guess that's why the edge of the distortion (as visible on a software crash) is crisp compared to the center, and also why FFR exists. (Sidenote, maybe clientside FFR should be used to allow high resolutions?)

Since the Quest resolution is warped and querying a resolution value that compensates for this is impossible, this issue is invalid.
