### ISSUE TITLE
Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:32 Arch Linux Error.

### ISSUE THREAD

**Issue by jonahnm** [alvr-org/ALVR#730]
After connecting the headset to the server the client crashes and the server shows this error: `Client disconnected. Cause:At alvr/common/src/sockets/control_socket.rs:32.` The steamVR shows the preview for a minute but then it goes away.
EDIT:
this: https://pastebin.com/YuspgFyN is the crash log

**Comment by yackaro** [comment]
In your log, ALVR doesn't seem to be able to find an installation of Chrome/chromium, which is required for the web dashboard to function.
If you want my _personal_ recommendation, try [Ungoogled Chromium.](https://aur.archlinux.org/packages/ungoogled-chromium/)
Build times are on the very long side for it, so I recommend installing it via the chaotic-aur repository.
ALVR works fine with detecting and using it as for the dashboard on my system, so it should work for you as well.
Otherwise, you could just install the regular chromium branch off the official repos, that will work just as well.
