### ISSUE TITLE
why the default value of the tracking_interval in the tracking_loop  is 1/360 ?

### ISSUE THREAD

**Issue by chiwangnvp** [alvr-org/ALVR#747]
![image](https://user-images.githubusercontent.com/45933755/126731521-94a60d67-d466-4da7-af83-a9c63bd2766e.png)

**Comment by chiwangnvp** [comment]
Can we decrease it onto 1/90 ?

**Comment by IssacDowling** [comment]
Surely it should be 1/120, otherwise people on 120hz would have issues

**Comment by Killrmemz** [comment]
I'd think it could be configurable, set to either 1/50 or 1/60. 1/50 and 1/60 because those are the two polling rates for tracking on the hardware side, which I'm pretty sure is actually mostly just the cameras' framerate options, and possibly a matching flicker cycle of the IR rings of the controllers. Perhaps the 1/360 is to get info from any Quest-side tracking smoothing+prediction that Facebookulus is probably doing to upsample the 50/60Hz to 72/80/90/120Hz.

**Comment by korejan** [comment]
This wasn't a hard-coded value before, current value is fixed to 3x120hz, origionally it was parameterized by which ever refresh rate was selected but it was still 3x that amount. Earlier this year we had a dicussion about why the tracking rate is set to 3x the selected display refresh rate and it was something to do with latency, but i don't remember now. Basically the same tracking data for one frame will get sent multiple times.

**Comment by korejan** [comment]
What I wrote may not be entirely true anymore with the recent changes, there might be some extrapolation going based on the time passed to the OVR function of get the controller poses.
@sctanf

**Comment by chiwangnvp** [comment]
Thank you for your replies though.
