### ISSUE TITLE
Heavy pixelation, 

### ISSUE THREAD

**Issue by LudoDash** [alvr-org/ALVR#795]
### Bug reports:

Heavy pixelation, visual glitches, screen tearing.
no games running, only steam vr

(Not a bandwidth issue, headset runs fine at 200Mb/s on both VD and Airlink)

#### Environment

Ryzen 5 3600
RTX 3060
Quest 2
Latest release:
ALVR v16.0.0
Windows is up to date
Ver: 21H1

5.8ghz
802.11/ac

Video bitrate: 150
Refresh rate: 90hz
Codec: HEVC

**Comment by dragonjesse95** [comment]
Try lowering the bit rate to find a "sweet spot", maybe somewhere between 30 and 50 Mb/s. Higher and lower bandwidth come with their own tradeoffs, and I think that what you have is probably just too high. When the bitrate is higher, it takes longer for the headset to decode, which can lead to issues. Try changing it down to 30 Mb/s and see if that fixes it. Otherwise, no idea what the problem is. :/
