### ISSUE TITLE
Host frequently completely freezes, displaying weird graphics

### ISSUE THREAD

**Issue by tcrass** [alvr-org/ALVR#958]
## Description

Quite frequently after an unsuccessful connection attempt from the client (Oculus Quest 2), my KDE desktop completeley freezes, displaying some weirdly distorted graphics. Some examples:
![IMG_20220208_104836](https://user-images.githubusercontent.com/6480173/152973101-b713fc4d-35df-4c98-b6ce-818a2b74f3e8.jpg)
![IMG_20220208_113028](https://user-images.githubusercontent.com/6480173/152973130-3ea0c468-7917-4729-bf72-5809bfe27c47.jpg)
Sometimes I can switch over to one of the virtual consoles or zap the X server, sometimes the system is completely frozen; but even in the former case, I'm usually  unable to restart X (when I do so, the system just hangs).

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

https://linux-hardware.org/?probe=bc0462d8e3

**CPU**:

**GPU**:

**Audio**:

### Installation
**ALVR Version**:

17.0.1+1643781622+0541c19e on both client and server

**SteamVR Version**:

1.20.4
**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

Debian GNU/Linux 11 (bullseye) (up-to-date)

**Comment by tcrass** [comment]
Last time this happened, I managed to switch to a virtual terminal, where the following message was printed repeatedly in an interval of a few seconds:

`[drm:amdgpu_job_timeout [amdgpu]] *ERROR* ring gfx timeout, but soft recovered`

Any ideas...?

**Comment by mittorn** [comment]
Try this:
1. disable steamvr home, this should fix gfx ring failure on polaris, but it still crashes for me in comp ring
2. disable async reprojection (`"enableLinuxVulkanAsync": false` in `SteamVR/resources/settings/default.vrsettings` )
3. disable realtime SteamVR capabilities:
add `return 0` in `SteamVR/bin/vrstartup.sh` here:
```
function SteamVRLauncherSetup()
{
        return 0
```
and reset capabilities on `bin/linux64/vrcompositor-launcher` by setcap -r
```
setcap -r ~/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrcompositor-launcher
```
Last step will not work if you are using SteamVR 1.14, because of bug in SDL, but should work with recent versions, disabling async reprojection should fix jitter on recent SteamVR versions. Disabling realtime capabilities seems to fix most of GPU hangs, realtime vulkan vrcompositor implementation seems to do some weird things.
And it is recommended to use recent git mesa version on polaris because they committed very important fix: :https://www.phoronix.com/scan.php?page=news_item&px=AMD-VCE-Better-Speed

**Comment by mittorn** [comment]
Did it fix GPU crash? Recent alvr nightly disabled async reprojection by default. The only thing left is disabling realtime priority if it still works unstable with amd (but it maybe kernel-specific)

**Comment by tcrass** [comment]
I'm currently unable to do any further investigation since for the last few days SteamVR has been refusing to start, complaining about "a key component not working properly (307)". I'll keep trying, though, always using the latest ALVR from master, compilation of which works like a charm. Great build script! :)

**Comment by ColdIce1605** [comment]
@tcrass please read the release notes
On AMD GPUs you need to downgrade Mesa to 21.0. If you can’t downgrade Mesa and want to keep the previous behavior (jitter) you have to enable async reprojection in Settings->Video->Advanced options. Failing to do so will result in SteamVR crashing with error 307.

**Comment by ColdIce1605** [comment]
> l'll keep trying, though, always using the latest ALVR from master, compilation of which works like a charm. Great build script! :)
thats because what you need to do in the release version has been automated using stuff from wgpu to detect your vendor and apply that setting accordingly 
As this issue really doesn't have a use being open as its own and everything that can be done is done other than releasing a new version with the automated patch I would close this.

**Comment by ColdIce1605** [comment]
Also in the patch notes(nevermind not in the patch notes :eyes: ) you aren't suppose to put on your headset before setting that setting failing to do so will guarantee a crash.

**Comment by tcrass** [comment]
Hi ColdIce1605,

> As this issue really doesn't have a use being open as its own and everything that can be done is done other than releasing a new version with the automated patch I would close this.

agreed!

However...

> @tcrass please read the release notes

...I'm not quite sure which release/patch notes you are referring to (ALVR? Mesa? Which version/commit?). Could you please provide a link?

Cheers --
Torsten
