### ISSUE TITLE
Is there a plan that ALVR supports kcp network protocol ?

### ISSUE THREAD

**Issue by chiwangnvp** [alvr-org/ALVR#970]

**Comment by zarik5** [comment]
I've never heard of KCP before. It seems it is very similar to QUIC but with FEC integration. QUIC with FEC was postponed to a future draft. In the issue #886 I explain how we could implement a QUIC-based StreamSocket with optional FEC support. Ultimately I prefer QUIC instead of KCP because it's much more tried and tested.

**Comment by chiwangnvp** [comment]
Got it! The reason I ask this question is that in some network environment, we found lots of missing network packets during streaming when we used UDP.  But while we changed onto TCP, the phenomenon of missing network packets were gone. And KCP was some improved udp protocol for my knowledge. Here is some implementation of KCP：https://github.com/en/kcp-rs I downloaded it and try to run the examples there. And It actually worked!
Anyway, thank you for let me about your big plan about QUIC + FEC.
