### ISSUE TITLE
Add no-video option

### ISSUE THREAD

**Issue by DavidGasku** [alvr-org/ALVR#974]
It would be very useful to develop, just using controllers to test interactions, but without the overload of encoding and transmitting the video to the headset.

It could be usable even in humble laptops to develop anywhere under linux.

**Comment by zarik5** [comment]
@korejan fork should be able to work without the Quest HMD, but only if a wired headset is connected. This is a SteamVR requirement. Monado supports headless mode, but it's not compatible with ALVR yet

**Comment by korejan** [comment]
> @korejan fork should be able to work without the Quest HMD, but only if a wired headset is connected. This is a SteamVR requirement. Monado supports headless mode, but it's not compatible with ALVR yet

This feature has been in main since before v16, it's in the headset settings, advance option "Tracking Reference Only".

Yes normally you need to use another main headset for SteamVR to run but if you don't you can get around this via using **null driver**, this driver comes with SteamVR you use just have to enable it.

The only issue of doing this is there no space calibration, for that you will rely on a 3rd party tool such as OpenVR Space Calibrator but there's no way you can calibrate against the null driver as there's no physical device to use. I don't know what will happen if you just use it uncalibrated, most likely the controllers will be in completely incorrect position & orientation relative to the null_driver "hmd". Maybe try using local tracking space.
